services:
  _defaults:
    autowire: true
    autoconfigure: true

  Infinity\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Enum/'
      - '../src/Exception/'
      - '../src/Interfaces/'
      - '../src/Traits/'
      - '../src/InfinityBundle.php'

  Infinity\Controller\:
    resource: '../src/Controller/'
    tags:
      - 'controller.service_arguments'

  Infinity\Interfaces\ResourceServiceInterface:
    alias: Infinity\Service\ResourceService