name: Build php-fpm

on: [push]

env:
  IMAGE_NAME: lypage-php-fpm
  DOCKERFILE_PATH: docker/build/php-fpm/Dockerfile

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: /vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: php-actions/composer@v6
        with:
          php_version: 8.1
          command: --no-interaction --no-scripts

  phpstan:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: /vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: PHPStan
        uses: php-actions/phpstan@v2
        with:
          configuration: phpstan.neon.dist
          memory_limit: 256M

  php-cs-fixer:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: /vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php_version: 8.1

      - name: whatever
        run: |
          ls -la .
          ls -la vendor/

      - name: PHP-CS-Fixer
        run: |
          vendor/bin/php-cs-fixer fix --config ./.php-cs-fixer.dist.php --dry-run --diff --ansi